from django.conf import settings

KEY_LENGTH = 32

TOKEN_KEY_LENGTH = 64
ACCOUNT_KEY_LENGTH = 32
CONSUMER_ID_LENGTH = 24
CONSUMER_SECRET_LENGTH = 32
ACCOUNT_KEY_LENGTH = 32

PREFERENCES = getattr(settings, "PREFERENCES", ())

